<?php 
include('header.php');
?>
<div class="bodyWrap">
	<h1>The Fourth Branch Privacy Policy</h1>
	<p>This Privacy Policy describes how and when The Fourth Branch collects, uses and shares your information when you use our Services. The Fourth Branch receives your information through our various websites, SMS, APIs, email notifications, applications, buttons, widgets, ads, and commerce services (the "Services" or "The Fourth Branch") and from our partners and other third parties. For example, you send us information when you use The Fourth Branch from our website, post or receive messages via SMS, or access The Fourth Branch from an application such as The Fourth Branch for Mac or The Fourth Branch for Android. When using any of our Services you consent to the collection, transfer, manipulation, storage, disclosure and other uses of your information as described in this Privacy Policy. Irrespective of which country you reside in or supply information from, you authorize The Fourth Branch to use your information in the United States and any other country where The Fourth Branch operates.</p>
	<h3>Information Collection and Use</h3>
	<h4>Basic Account Information:</h4>
	<p>When you create or reconfigure a The Fourth Branch account, you provide some personal information, such as your name, username, password, email address, etc. Your username is listed publicly on our Services, including on your profile page and in search results. Some Services, such as search and public user profiles, do not require registration.</p>
	<h4>Additional Information:</h4>
	<p>You may provide us with profile information to make public, such as a short biography, your location, your website, or a picture. You may provide information to customize your account, such as a cell phone number for the delivery of SMS messages. We may use your contact information to send you information about our Services or to market to you. We may use your contact information to help others find you’re The Fourth Branch account, including through third-party services and client applications. You may choose to upload your address book so that we can help you find The Fourth Branch users you know or help other The Fourth Branch users find you. We may later make suggestions to you and other users on The Fourth Branch based on imported address book contacts. If you email us, we may keep your message, email address and contact information to respond to your request. If you connect you’re The Fourth Branch account to your account on another service in order to cross-post between The Fourth Branch and that service, the other service may send us your registration or profile information on that service and other information that you authorize. This information enables cross-posting, helps us improve the Services.</p>
	<h4>Following, Lists and other Public Information:</h4>
	<p>Our Services are primarily designed to help you share your political opinion with the world. Most of the information you provide us is information you are asking us to make public. This includes not only comments and the metadata provided with comments, but also the people you follow, the comments you vote on, and many other bits of information that result from your use of the Services. We may use this information to customize the content we show you, including ads. Our default is almost always to make the information you provide public for as long as you do not delete it from The Fourth Branch, but we generally give you settings to make the information more private if you want. Our Services broadly and instantly disseminate your public information to a wide range of users, customers, and services. For instance, your public user profile information and public comments are immediately delivered via SMS and our APIs to our partners and other third parties, including search engines, developers, and publishers that integrate The Fourth Branch content into their services, and institutions such as universities and public health agencies that analyze the information for trends and insights. When you share information or content you should think carefully about what you are making public.</p>
	<h4>Location Information:</h4>
	<p>You may choose to publish your location in you’re The Fourth Branch profile. We may also use other data from your device to determine location, for example, information about wireless networks or cell towers near your mobile device, or your IP address. We may use and store information about your location to provide features of our Services, and to improve and customize the Services.</p>
	<h4>Links:</h4>
	<p>The Fourth Branch may keep track of how you interact with links across our Services, including our email notifications, third-party services, and client applications, by redirecting clicks or through other means. We do this to help improve our Services, to provide more relevant advertising, and to be able to share aggregate click statistics such as how many times a particular link was clicked on.</p>
	<h4>Cookies:</h4>
	<p>Like many websites, we use cookies and similar technologies to collect additional website usage data and to improve our Services, but we do not require cookies for many parts of our Services such as searching and looking at public user profiles. A cookie is a small data file that is transferred to your computer's hard disk. The Fourth Branch may use both session cookies and persistent cookies to better understand how you interact with our Services, to monitor aggregate usage by our users and web traffic routing on our Services, and to customize and improve our Services. Most Internet browsers automatically accept cookies. You can instruct your browser, by changing its settings, to stop accepting cookies or to prompt you before accepting a cookie from the websites you visit. However, some Services may not function properly if you disable cookies.</p>
	<h4>Log Data:</h4>
	<p>When you use our Services, we may receive information ("Log Data") such as your IP address, browser type, operating system, the referring web page, pages visited, location, your mobile carrier, device information (including device and application IDs), search terms, and cookie information. We receive Log Data when you interact with our Services, for example, when you visit our websites, sign into our Services, interact with our email notifications, use you’re The Fourth Branch account to authenticate to a third-party website or application. We may also receive Log Data when you click on, view or interact with a link on our Services to a third-party application, such as when you choose to install another application through The Fourth Branch. The Fourth Branch uses Log Data to provide, understand, and improve our Services. If not already done earlier, we will either delete Log Data or remove any common account identifiers, such as your username, full IP address, or email address, after 18 months.</p>
	<h4>Commerce Services:</h4>
	<p>You may provide your payment information, including your credit or debit card number, card expiration date, CVV code, and billing address (collectively, "Payment Information"), along with your shipping address, to complete a commerce transaction on The Fourth Branch. You may also provide your credit or debit card number to register for card-linked services, such as offers. To facilitate future purchases on The Fourth Branch, we store your Payment Information. We consider your Payment Information and shipping address private and do not make such information public. We collect and store information created by your purchases made on The Fourth Branch ("Transaction Data"). If you register your credit or debit card with The Fourth Branch for card-linked services, we receive information about the card transactions from a third-party payment services provider ("Registered Card Data"). Transaction Data and Registered Card Data may include the merchant’s name and the date, time and amount of the transaction. The Fourth Branch uses Registered Card Data to verify eligibility for card-linked services, and may also use Registered Card Data to limit the number of offers available to you and keep track of your offers.</p>
	<h4>Third-Parties and Affiliates:</h4>
	<p>The Fourth Branch uses a variety of third-party services to help provide our Services, such as hosting our various blogs and wikis, and to help us understand and improve the use of our Services, such as Google Analytics. These third-party service providers may collect information sent by your browser as part of a web page request, such as cookies or your IP address. Third-party ad partners may share information with us, like a browser cookie ID, website URL visited, mobile device ID, or cryptographic hash of a common account identifier (such as an email address), to help us measure and tailor ads. For example, this allows us to display ads about things you may have already shown interest in. We may also receive information about you from our corporate affiliates in order to help provide, understand, and improve our Services and our affiliates’ services, including the delivery of ads.</p>
	<h3>Information Sharing and Disclosure</h3>
	<h4>Your Consent:</h4>
	<p>We may share or disclose your information at your direction, such as when you authorize a third-party web client or application to access you’re The Fourth Branch account.</p>
	<h4>Service Providers:</h4>
	<p>We engage service providers to perform functions and provide services to us in the United States and abroad. We may share your private personal information with such service providers subject to confidentiality obligations consistent with this Privacy Policy, and on the condition that the third parties use your private personal data only on our behalf and pursuant to our instructions. We share your Payment Information with payment services providers to process payments; prevent, detect and investigate fraud or other prohibited activities; facilitate dispute resolution such as chargebacks or refunds; and for other purposes associated with the acceptance of credit or debit cards. We may share your credit or debit card number with payment services providers, or third parties authorized by them, to monitor card transactions at participating merchants and track redemption activity for the purposes of providing card-linked services.</p>
	<h4>Sellers of Goods and Services:</h4>
	<p>If you buy goods or services on The Fourth Branch, we may provide the seller, commerce provider or marketplace with your name, email address, shipping address, Payment Information and Transaction Data to facilitate payment processing, order fulfillment and dispute resolution (including payment and shipping disputes) and to help prevent, detect and investigate fraud or other prohibited activities. Please refer to these third parties’ privacy policies for information about their privacy practices.</p>
	<h4>Law and Harm:</h4>
	<p>Notwithstanding anything to the contrary in this Policy, we may preserve or disclose your information if we believe that it is reasonably necessary to comply with a law, regulation or legal request; to protect the safety of any person; to address fraud, security or technical issues; or to protect The Fourth Branch’s rights or property. However, nothing in this Privacy Policy is intended to limit any legal defenses or objections that you may have to a third party’s, including a government’s, request to disclose your information.</p>
	<h4>Business Transfers and Affiliates:</h4>
	<p>In the event that The Fourth Branch is involved in a bankruptcy, merger, acquisition, reorganization or sale of assets, your information may be sold or transferred as part of that transaction. This Privacy Policy will apply to your information as transferred to the new entity. We may also disclose information about you to our corporate affiliates in order to help provide, understand, and improve our Services and our affiliates’ services, including the delivery of ads.</p>
	<h4>Non-Private or Non-Personal Information:</h4>
	<p>We may share or disclose your non-private, aggregated or otherwise non-personal information, such as your public user profile information, public comments, the people you follow or that follow you, or the number of users who clicked on a particular link (even if only one did), or reports to advertisers about unique users who saw or clicked on their ads after we have removed any private personal information (such as your name or contact information).</p>
	<h4>Modifying Your Personal Information</h4>
	<p>If you are a registered user of our Services, we provide you with tools and account settings to access or modify the personal information you provided to us and associated with your account.</p>
	<h4>Our Policy Towards Children</h4>
	<p>Our Services are not directed to persons under 13. If you become aware that your child has provided us with personal information without your consent, please contact us at privacy@thefourthbranch.co. We do not knowingly collect personal information from children under 13. If we become aware that a child under 13 has provided us with personal information, we take steps to remove such information and terminate the child's account. </p>
	<h4>Changes to this Policy</h4>
	<p>We may revise this Privacy Policy from time to time. If we make a change to this policy that, in our sole discretion, is material, we will notify you via email to the email address associated with your account. By continuing to access or use the Services after those changes become effective, you agree to be bound by the revised Privacy Policy.</p>
	<p><i>Effective: September 30, 2014</i></p>
</div>
<?
include('footer.php');
?>